= Query Parameter JPA
Manuel Doncel Martos <https://github.com/manuelarte[@manuelarte]>
// Settings:
:latest-version: 0.0.2
:status:

:url-repo: https://github.com/manuelarte/query-parameter-jpa
:url-issues: {url-repo}/issues
:url-search-issues: {url-repo}/search?type=Issues

:url-ci-circleci: https://circleci.com/gh/manuelarte/query-parameter-jpa

ifdef::status[]
// image:https://img.shields.io/gem/v/jekyll-asciidoc.svg[Latest Release, link={url-maven}]
image:https://img.shields.io/badge/license-MIT-blue.svg[MIT License, link=#copyright-and-license]
image:https://circleci.com/gh/manuelarte/query-parameter-jpa.svg?style=shield[Build status (Circle CI), link={urc-ci-circleci}]
image:https://img.shields.io/badge/version-{latest-version}-blue[Release version]
endif::[]

:toc: []

== Overview

JPA Query Param is a library that allows you to add a query parameter to your endpoints.

== Prerequisites

- Java 8 or above
- Spring Data JPA
- The repositories you want to query needs to implement JpaSpecificationExecutor<T>

== Installation

Add the following dependency in your project to start using Query Parameter JPA.

[source,bash]
----
implementation 'org.manuel.spring:query-parameter-jpa:{latest-version}'
----

== Usage

Add the @EnableQueryParameter annotation in your spring boot application, to import the configuration.

[source,java]
----
@SpringBootApplication
@EnableQueryParameter
public class SpringBootAppApplication {
----

Then add the @QueryParameter annotation in a controller you would like to use the query param.
Here you can see an example:

[source,java]
----
@GetMapping(produces = MediaType.APPLICATION_JSON_VALUE)
public ResponseEntity<List<Entity>> findByQuerying(@QueryParameter(entity = Entity.class) Specification<Entity> query) {
  return ResponseEntity.ok(entityService.findAll(query));
}
----

Then call that endpoint and use the available query operations:

[source,bash]
----
GET /entities?q=firstName::Manuel;age:<18
----

== Query Operations supported

=== Equals (::)

Below an example to match firstName == Manuel
[source,bash]
----
GET /entities?q=firstName::Manuel
----

=== Lower than (:<)

Below an example to match age < 18
[source,bash]
----
GET /entities?q=age:<18
----

=== Lower than or equal (:<=)

Below an example to match age <= 18
[source,bash]
----
GET /entities?q=age:<=18
----

=== Greater than (:>)

Below an example to match age > 18
[source,bash]
----
GET /entities?q=age:>18
----

=== Greater than or equal (:>=)

Below an example to match age >= 18
[source,bash]
----
GET /entities?q=age:>=18
----

=== In (:in:(xxx,yyy,...))

Below an example get gender in MALE and FEMALE
[source,bash]
----
GET /entities?q=gender:in:(MALE,FEMALE)
----

== Concatenate params

It's possible to concatenate params AND (;), OR (|).

As an example:
If we want entities whose firstname is Manuel *and* age less than 18
[source,bash]
----
GET /entities?q=firstName::Manuel;age:<18
----
If we want entities whose firstname is Manuel *or* age less than 18
[source,bash]
----
GET /entities?q=firstName::Manuel|age:<18
----

== Customization

=== Keys filtering

It's possible to filter the keys that are allow or not allow to be queried (by default every key is allowed).
As an example, if I only want to query by firstName and lastName
[source,java]
----
@GetMapping(produces = MediaType.APPLICATION_JSON_VALUE)
public ResponseEntity<List<Entity>> findByQuerying(@QueryParameter(entity = Entity.class, allowedKeys={"firstName", "lastName"}) Specification<Entity> query) {
  return ResponseEntity.ok(entityService.findAll(query));
}
----
Or if only want to not allow createdBy field
[source,java]
----
@GetMapping(produces = MediaType.APPLICATION_JSON_VALUE)
public ResponseEntity<List<Entity>> findByQuerying(@QueryParameter(entity = Entity.class, notAllowedKeys="createdBy") Specification<Entity> query) {
  return ResponseEntity.ok(entityService.findAll(query));
}
----

Then the parser will throw a QueryParserException if finds a not allowed key.

== Contributing
Pull requests are welcome. For major changes, please open an issue first to discuss what you would like to change.

Please make sure to update tests as appropriate.

== License
[MIT](https://choosealicense.com/licenses/mit/)