= Query Parameter JPA
Manuel Doncel Martos <https://github.com/manuelarte[@manuelarte]>
// Settings:
:latest-version: 0.0.2
:status:

:url-repo: https://github.com/manuelarte/query-parameter-jpa
:url-issues: {url-repo}/issues
:url-search-issues: {url-repo}/search?type=Issues

:url-ci-circleci: https://circleci.com/gh/manuelarte/query-parameter-jpa

ifdef::status[]
image:https://img.shields.io/badge/license-MIT-blue.svg[MIT License, link=#copyright-and-license]
image:https://circleci.com/gh/manuelarte/query-parameter-jpa.svg?style=shield[Build status (Circle CI), link={urc-ci-circleci}]
image:https://img.shields.io/badge/version-{latest-version}-blue[Release version]
endif::[]

:toc: []

== Overview

JPA Query Param is a library that allows you to add a query parameter to your endpoints.

== Prerequisites

- Java 8 or above
- Spring Data JPA
- The repositories you want to query needs to implement JpaSpecificationExecutor<T>

== Installation

Add the following dependency in your project to start using Query Parameter JPA.

[source,bash]
----
implementation 'org.manuel.spring:query-parameter-jpa:{latest-version}'
----

== Usage

include::https://github.com/manuelarte/query-parameter-model/blob/constraints/queryparameter.adoc[]

== Customization

include::https://github.com/manuelarte/query-parameter-model/blob/constraints/constraints.adoc[]

==== Example of Query Param annotations

:sourcedir-example-model: spring-boot-example/src/main/java/io/github/manuelarte/spring/queryparameter/jpa/example/model/entities

[source,java]
----
include::{sourcedir-example-model}/Example2.java[]
----

In this example, if we are going to query the Example2 entity, the field _firstName_ is mandatory

== Contributing
Pull requests are welcome. For major changes, please open an issue first to discuss what you would like to change.

Please make sure to update tests as appropriate.

== License
[MIT](https://choosealicense.com/licenses/mit/)